name: SDF Validation
run-name: validate
on: [push]
jobs:
    sdf-validate:
        runs-on: ubuntu-latest
        environment: Sanbox
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 'lts/*'

            - name: Install JDK
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'oracle'

            - name: Run NPM install
              run: npm install --acceptsuitecloudsdklicense
              

            - name: Run Unit Test
              run: npm test

            - name: Authenticate Project againts ${{vars.NS_ACCOUNT_ID}}
              run: ./node_modules/.bin/suitecloud account:savetoken --account ${{vars.NS_ACCOUNT_ID}} --authid ${{vars.NS_ACCOUNT_ID}} --tokenid ${{secrets.NS_TOKEN_ID}} --tokensecret ${{secrets.NS_TOKEN_SECRET}}

            - name: Run Unit Test
              run: npm run validate